# Generated by Django 4.2.6 on 2023-10-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_2',
            },
        ),
        migrations.CreateModel(
            name='Profile_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_3',
            },
        ),
        migrations.CreateModel(
            name='Profile_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_4',
            },
        ),
        migrations.CreateModel(
            name='Profile_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_5',
            },
        ),
        migrations.CreateModel(
            name='Profile_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_6',
            },
        ),
        migrations.CreateModel(
            name='Profile_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_7',
            },
        ),
        migrations.CreateModel(
            name='Profile_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_8',
            },
        ),
        migrations.CreateModel(
            name='Profile_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile_1',
            },
        ),
    ]
