# Generated by Django 4.2.6 on 2023-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_2_profile_3_profile_4_profile_5_profile_6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=300)),
                ('rated', models.CharField(max_length=300)),
                ('easy', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='pros')),
            ],
            options={
                'verbose_name_plural': 'About_1',
            },
        ),
        migrations.CreateModel(
            name='About_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=300)),
                ('rated', models.CharField(max_length=300)),
                ('easy', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='pros')),
            ],
            options={
                'verbose_name_plural': 'About_2',
            },
        ),
    ]
