# Generated by Django 4.2.6 on 2023-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_about_1_about_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=300)),
                ('rated', models.CharField(max_length=300)),
                ('easy', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='pros')),
            ],
            options={
                'verbose_name_plural': 'About_2',
            },
        ),
    ]
