# Generated by Django 4.2.6 on 2023-10-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'home'},
        ),
        migrations.RenameField(
            model_name='home',
            old_name='easy',
            new_name='Legit',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='quality',
            new_name='properties',
        ),
    ]
